In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.qualifying_lap_time`
# WHERE YEAR=2023
# AND GP='Spanish Grand Prix'
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
track2=track3[(track3["GP"]=='Qatar Grand Prix')&(track3["Year"]==2025)]
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [5]:
Drivers=(track2['Driver'].unique())
Drivers

array(['PIA', 'NOR', 'VER', 'RUS', 'ANT', 'HAD', 'SAI', 'ALO', 'GAS',
       'LEC', 'HUL', 'LAW', 'BEA', 'BOR', 'ALB', 'TSU', 'OCO', 'HAM',
       'STR', 'COL'], dtype=object)

In [6]:
track2["LapTime"].min()

'0 days 00:01:19.387000'

In [7]:
#Assign Rank for each entry point
track2["RK"] = track2.groupby(by=["Driver"])["LapTime"].rank(method="dense", ascending=True)
track2["RK"]= track2["RK"].astype(int)

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2442521796.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2["RK"] = track2.groupby(by=["Driver"])["LapTime"].rank(method="dense", ascending=True)
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2442521796.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2["RK"]= track2["RK"].astype(int)

In [8]:
track2.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,RK
691,0 days 00:16:06.031000,PIA,81,NaT,1.0,1.0,0 days 00:14:20.016000,NaT,NaT,0 days 00:00:35.764000,0 days 00:00:31.537000,NaT,0 days 00:15:34.494000,0 days 00:16:06.060000,225.0,229.0,284.0,92.0,False,SOFT,7.0,False,McLaren,0 days 00:14:20.016000,2025-11-29 18:02:43.713,1,NaN,False,,False,False,2025,Qatar Grand Prix,13
692,0 days 00:17:26.770000,PIA,81,0 days 00:01:20.739000,2.0,1.0,NaT,NaT,0 days 00:00:29.734000,0 days 00:00:27.306000,0 days 00:00:23.699000,0 days 00:16:35.765000,0 days 00:17:03.071000,0 days 00:17:26.770000,257.0,290.0,285.0,324.0,True,SOFT,8.0,False,McLaren,0 days 00:16:06.031000,2025-11-29 18:04:29.728,1,NaN,False,,False,True,2025,Qatar Grand Prix,6
693,0 days 00:19:10.980000,PIA,81,0 days 00:01:44.210000,3.0,1.0,NaT,0 days 00:19:06.773000,0 days 00:00:38.770000,0 days 00:00:31.806000,0 days 00:00:33.634000,0 days 00:18:05.540000,0 days 00:18:37.346000,0 days 00:19:10.980000,212.0,250.0,NaN,190.0,False,SOFT,9.0,False,McLaren,0 days 00:17:26.770000,2025-11-29 18:05:50.467,1,NaN,False,,False,False,2025,Qatar Grand Prix,7
694,0 days 00:22:58.389000,PIA,81,NaT,4.0,2.0,0 days 00:21:21.227000,NaT,NaT,0 days 00:00:30.175000,0 days 00:00:32.666000,NaT,0 days 00:22:25.723000,0 days 00:22:58.552000,230.0,267.0,285.0,107.0,False,SOFT,1.0,True,McLaren,0 days 00:19:10.980000,2025-11-29 18:07:34.677,1,NaN,False,,False,False,2025,Qatar Grand Prix,13
695,0 days 00:24:18.623000,PIA,81,0 days 00:01:20.234000,5.0,2.0,NaT,NaT,0 days 00:00:29.557000,0 days 00:00:27.151000,0 days 00:00:23.526000,0 days 00:23:27.946000,0 days 00:23:55.097000,0 days 00:24:18.623000,259.0,290.0,286.0,325.0,True,SOFT,2.0,True,McLaren,0 days 00:22:58.389000,2025-11-29 18:11:22.086,1,NaN,False,,False,True,2025,Qatar Grand Prix,5

In [9]:
track_fastest=track2[track2['RK']==1]

In [10]:
pole_lap = track_fastest["LapTime"].min()
track_fastest['LapTimeDelta']= pd.to_timedelta(track_fastest["LapTime"]) - pd.to_timedelta(pole_lap)
track_fastest['LapTimeDelta']=track_fastest['LapTimeDelta'].astype(str)

for index, row in track_fastest.iterrows():
  if track_fastest.loc[index, 'LapTimeDelta']=='0 days 00:00:00':
    track_fastest.loc[index, 'LapTimeDelta']='0 days 00:00:00.01'
track_fastest['LapTimeDelta']=pd.to_timedelta(track_fastest['LapTimeDelta'])
track_fastest

track_fastest['LapTimeDelta'] = track_fastest['LapTimeDelta'] + pd.to_datetime('1970/01/01')

track_fastest['LapTimeDelta2']= pd.to_timedelta(track_fastest["LapTime"]) - pd.to_timedelta(pole_lap)
track_fastest['LapTimeDelta2']=track_fastest['LapTimeDelta2'].astype(str)

track_fastest["LapTimeDelta2"]=track_fastest['LapTimeDelta2'].str.split('days ').str[1]

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest['LapTimeDelta']= pd.to_timedelta(track_fastest["LapTime"]) - pd.to_timedelta(pole_lap)
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest['LapTimeDelta']=track_fastest['LapTimeDelta'].astype(str)
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest['LapTimeDelta']=pd.to_timedelta(track_fastest['LapTimeDelta'])
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest['LapTimeDelta'] = track_fastest['LapTimeDelta'] + pd.to_datetime('1970/01/01')
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest['LapTimeDelta2']= pd.to_timedelta(track_fastest["LapTime"]) - pd.to_timedelta(pole_lap)
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest['LapTimeDelta2']=track_fastest['LapTimeDelta2'].astype(str)
/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_45490/2506531996.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_fastest["LapTimeDelta2"]=track_fastest['LapTimeDelta2'].str.split('days ').str[1]

In [ ]:
# track_fastest=track_fastest[track_fastest["Driver"]!='TSU']
# remove=(track_fastest["LapNumber"]==15)&(track_fastest["Driver"]=="ALB")
# track_fastest=track_fastest[~remove]
track_fastest.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,RK,LapTimeDelta,LapTimeDelta2
707,0 days 01:17:14.614000,PIA,81,0 days 00:01:19.387000,17.0,6.0,NaT,NaT,0 days 00:00:29.209000,0 days 00:00:26.919000,0 days 00:00:23.259000,0 days 01:16:24.436000,0 days 01:16:51.355000,0 days 01:17:14.614000,262.0,291.0,285.0,325.0,True,SOFT,2.0,True,McLaren,0 days 01:15:55.227000,2025-11-29 19:04:18.924,1,0.0,False,,False,True,2025,Qatar Grand Prix,1,1970-01-01 00:00:00.010,00:00:00
722,0 days 01:03:38.821000,NOR,4,0 days 00:01:19.495000,14.0,5.0,NaT,NaT,0 days 00:00:29.212000,0 days 00:00:26.978000,0 days 00:00:23.305000,0 days 01:02:48.538000,0 days 01:03:15.516000,0 days 01:03:38.821000,259.0,291.0,285.0,323.0,True,SOFT,2.0,True,McLaren,0 days 01:02:19.326000,2025-11-29 18:50:43.023,1,0.0,False,,False,True,2025,Qatar Grand Prix,1,1970-01-01 00:00:00.108,00:00:00.108000
747,0 days 01:17:29.505000,VER,1,0 days 00:01:19.651000,22.0,5.0,NaT,NaT,0 days 00:00:29.160000,0 days 00:00:27.064000,0 days 00:00:23.427000,0 days 01:16:39.014000,0 days 01:17:06.078000,0 days 01:17:29.505000,258.0,289.0,284.0,327.0,True,SOFT,2.0,True,Red Bull Racing,0 days 01:16:09.854000,2025-11-29 19:04:33.551,1,0.0,False,,False,True,2025,Qatar Grand Prix,1,1970-01-01 00:00:00.264,00:00:00.264000
773,0 days 01:18:14.205000,RUS,63,0 days 00:01:19.662000,25.0,5.0,NaT,NaT,0 days 00:00:29.246000,0 days 00:00:26.987000,0 days 00:00:23.429000,0 days 01:17:23.789000,0 days 01:17:50.776000,0 days 01:18:14.205000,258.0,292.0,285.0,325.0,True,SOFT,3.0,True,Mercedes,0 days 01:16:54.543000,2025-11-29 19:05:18.240,1,0.0,False,,False,True,2025,Qatar Grand Prix,1,1970-01-01 00:00:00.275,00:00:00.275000
795,0 days 01:17:42.763000,ANT,12,0 days 00:01:19.846000,21.0,6.0,NaT,NaT,0 days 00:00:29.331000,0 days 00:00:26.954000,0 days 00:00:23.561000,0 days 01:16:52.248000,0 days 01:17:19.202000,0 days 01:17:42.763000,258.0,292.0,284.0,325.0,True,SOFT,2.0,True,Mercedes,0 days 01:16:22.917000,2025-11-29 19:04:46.614,1,0.0,False,,False,True,2025,Qatar Grand Prix,1,1970-01-01 00:00:00.459,00:00:00.459000

In [19]:
fig=px.bar(
    track_fastest,
    y="Driver",
    x='LapTimeDelta',
    text='LapTimeDelta2',
    orientation='h',
    color='Driver',
    template="presentation",
    hover_data=['Team', 'Year', 'GP','LapTime', 'LapNumber','Sector1Time', 'Sector2Time', 'Sector3Time',
       'Compound', 'TyreLife', 'FreshTyre'],
    title="<b>Qualifying Delta vs. Fastest Lap for the {} {}</b>".format(year,gp),
    height=800, 
    width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "COL": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
                 }
)
fig.update_layout(
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),

    xaxis_title="<b>Delta</b>",
    yaxis_title="<b>Driver</b>",
    title_font_family="<b>PT Sans Narrow</b>",

)

fig.update_layout(xaxis_tickformat='%H:%M:%S.%f')

fig.update_traces(marker_line_width=1,marker_line_color="BLACK")

fig.update_layout(yaxis={'categoryorder':'total descending'})

fig.update_traces(textposition='auto')

fig.update_layout(
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=60, r=5, t=35, b=60),
)
fig.show()

In [20]:
save_year=2025

In [21]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Qualy Delta/{}/{} {} Qualifying Delta.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [22]:
#Multi GP Plot

In [28]:
save_year_multi=2025

In [29]:
#2025
race_multi=["Australian Grand Prix","Chinese Grand Prix","Japanese Grand Prix","Bahrain Grand Prix","Saudi Arabian Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Spanish Grand Prix","Canadian Grand Prix","Austrian Grand Prix","British Grand Prix","Belgian Grand Prix","Hungarian Grand Prix","Dutch Grand Prix","Italian Grand Prix","Azerbaijan Grand Prix","Singapore Grand Prix","United States Grand Prix","Mexico City Grand Prix","São Paulo Grand Prix","Las Vegas Grand Prix","Qatar Grand Prix"]
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2025
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    Drivers=(track2['Driver'].unique())
    track2["LapTime"].min()
    #Assign Rank for each entry point
    track2["RK"] = track2.groupby(by=["Driver"])["LapTime"].rank(method="dense", ascending=True)
    track2["RK"]= track2["RK"].astype(int)
    track_fastest=track2[track2['RK']==1]
    pole_lap = track_fastest["LapTime"].min()
    track_fastest['LapTimeDelta']= pd.to_timedelta(track_fastest["LapTime"]) - pd.to_timedelta(pole_lap)
    track_fastest['LapTimeDelta']=track_fastest['LapTimeDelta'].astype(str)

    for index, row in track_fastest.iterrows():
     if track_fastest.loc[index, 'LapTimeDelta']=='0 days 00:00:00':
        track_fastest.loc[index, 'LapTimeDelta']='0 days 00:00:00.01'
    track_fastest['LapTimeDelta']=pd.to_timedelta(track_fastest['LapTimeDelta'])
    track_fastest

    track_fastest['LapTimeDelta'] = track_fastest['LapTimeDelta'] + pd.to_datetime('1970/01/01')

    track_fastest['LapTimeDelta2']= pd.to_timedelta(track_fastest["LapTime"]) - pd.to_timedelta(pole_lap)
    track_fastest['LapTimeDelta2']=track_fastest['LapTimeDelta2'].astype(str)

    track_fastest["LapTimeDelta2"]=track_fastest['LapTimeDelta2'].str.split('days ').str[1]
    fig=px.bar(
        track_fastest,
        y="Driver",
        x='LapTimeDelta',
        text='LapTimeDelta2',
        orientation='h',
        color='Driver',
        template="presentation",
        hover_data=['Team', 'Year', 'GP','LapTime', 'LapNumber','Sector1Time', 'Sector2Time', 'Sector3Time',
        'Compound', 'TyreLife', 'FreshTyre'],
        title="<b>Qualifying Delta vs. Fastest Lap for the {} {}</b>".format(year_multi,i),
        height=800, 
        width=1200,
        color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "COL": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD" 
                    }
    )
    fig.update_layout(
        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),

        xaxis_title="<b>Delta</b>",
        yaxis_title="<b>Driver</b>",
        title_font_family="<b>PT Sans Narrow</b>",

    )

    fig.update_layout(xaxis_tickformat='%H:%M:%S.%f')

    fig.update_traces(marker_line_width=1,marker_line_color="BLACK")

    fig.update_layout(yaxis={'categoryorder':'total descending'})

    fig.update_traces(textposition='auto')

    fig.update_layout(
        title_x=0.5,
        hoverlabel=dict(
            bgcolor="white",
            font_size=16,
            font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=60, r=5, t=35, b=60),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Qualy Delta/{}/{} {} Qualifying Delta.html".format(save_year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:27: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:32: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:35: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:38: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:27: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:32: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:35: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:38: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:27: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:32: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:35: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:38: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:27: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:32: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:35: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:38: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:27: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:32: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:35: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:38: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:27: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:32: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:35: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:38: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_42689/464209130.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
