In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import matplotlib.pyplot as plt
import pandas_gbq
from PIL import Image
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
import fastf1
session = fastf1.get_session(2025, 'Australian Grand Prix', 'Q')
session.load()

circuit_info = session.get_circuit_info()

req         WARNING 	DEFAULT CACHE ENABLED! (6.23 GB) /Users/rdesh723/Library/Caches/fastf1
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.5.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

In [4]:
query2=f"""
SELECT
A.Year,
A.GP,
A.Driver,
A.DriverNumber,
A.Team,
CAST(A.Position AS INT64) Position,
Status,
A.LapStartTime,
A.Time LapEndTime,
B.Time as LapInstant,
A.LapTime,
CAST(LapNumber as INT64) LapNumber,
RPM,
Speed,
nGear,
Throttle,
Brake,
DRS,
Distance,
RelativeDistance,
DriverAhead,
DistanceToDriverAhead,
X,
Y,
Z,
CAST(Stint as INT64) Stint,
PitOutTime,
PitInTime,
Sector1Time,
Sector2Time,
Sector3Time,
Sector1SessionTime,
Sector2SessionTime,
Sector3SessionTime,
CAST(SpeedI1 AS INT64) SpeedI1,
CAST(SpeedI2 AS INT64) SpeedI2,
CAST(SpeedFL AS INT64) SpeedFL,
CAST(SpeedST AS INT64) SpeedST,
Compound,
CAST(TyreLife AS INT64) TyreLife,
FreshTyre,
TrackStatus,
Deleted,
DeletedReason
FROM `perceptive-ivy-290216.f1_api.qualifying_lap_time`  A
INNER JOIN
`perceptive-ivy-290216.f1_api.qualifying_telemetry_2025` B
ON B.SessionTime>=A.LapStartTime AND B.SessionTime<=A.Time
AND A.Driver=B.Driver
AND A.Year=B.Year
AND A.GP=B.GP
WHERE A.Year=2025
AND A.GP="Australian Grand Prix"
# AND A.DRIVER='HAM'
AND B.Year=2025
AND B.GP="Australian Grand Prix"
# AND B.Driver='HAM'
ORDER BY LapNumber, LapStartTime, LapInstant
"""
track1=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [5]:
track2=track1.copy()
year=track2['Year'][0]
gp=track2['GP'][0]

In [6]:
#Convert braking from True False to 0 & 1
def braking_ind(ind):
  if ind==True:
    return 1
  else:
    return 0

track2['Braking'] = track2['Brake'].apply(braking_ind)

In [7]:
track2["LapTime"]=track2['LapTime'].str.split('days ').str[1]
track2["LapTime"]=pd.to_datetime(track2['LapTime'],format='%H:%M:%S.%f')
track2["LapTime"]=track2["LapTime"].dt.strftime("%H:%M:%S.%f")

In [8]:
#Convert lapnumber to string for discrete chart coloring
track2["LapNumber"]=track2["LapNumber"].astype(str)

In [9]:
track2['Dist_Diff2'] = track2.groupby(["LapNumber","Driver"])["Distance"].shift(1)
# track2['Dist_Diff2'] = track2.groupby(["Driver"])["Distance"].shift(1) ## Use when not looking at just 1 lap
track2['Dist_Diff'] = track2['Distance']-track2["Dist_Diff2"]
track2["Dist_Diff_Sum"] = track2.groupby(by=["LapNumber","Driver"])["Dist_Diff"].cumsum()
# track2["Dist_Diff_Sum"] = track2.groupby(by=["Driver"])["Dist_Diff"].cumsum()  ## Use when not looking at just 1 lap

##Another way to calculate distances manually, if the distance column wasnt present in the data set. Dist_Diff_Sum AND Dist_Total Should match very closely which they do, even when using our own method

#Calculate the distance traversed in totality and then for each lap
track2['X_Diff'] = track2['X'] - track2['X'].shift(1)
track2['Y_Diff'] = track2['Y'] - track2['Y'].shift(1)
track2['Z_Diff'] = track2['Z'] - track2['Z'].shift(1)
track2['X_Diff']=track2['X_Diff'].pow(2)
track2['Y_Diff']=track2['Y_Diff'].pow(2)
track2['Z_Diff']=track2['Z_Diff'].pow(2)
track2['Dist']=track2['X_Diff']+track2['Y_Diff']+track2['Z_Diff']

#Distance between current point and previous data point
track2['Dist']=track2['Dist'].pow(1./2)
track2['Dist']=track2['Dist']/10

#Running sum of distance covered by a driver
track2['Dist_Total']=track2['Dist'].cumsum()

#Running sum of distance covered by a driver by lap
track2["Dist_Lap"] = track2.groupby(by=["LapNumber","Driver"])["Dist"].cumsum()

# #Drop columns that are not necessary anymore
# track2.drop(['X_Diff','Y_Diff','Z_Diff','Dist_Diff2'], axis=1, inplace=True)

# #Assign Rank for each entry point
track2["RK"] = track2.groupby(by=["LapNumber","Driver"])["LapInstant"].rank(method="dense", ascending=True)
track2["RK"]= track2["RK"].astype(int)
track2=track2.sort_values(by=['Driver','LapInstant'])

In [10]:
# track2[(track2["Driver"]=='HAM')&((track2["LapNumber"]=='1')|(track2["LapNumber"]=='2'))].sort_values(by=["LapNumber","LapInstant"])

In [11]:
# pd.DataFrame(track2.groupby(by=["Driver"])["LapTime"].unique())
Lap_Driver=pd.DataFrame(track2.groupby(by=["Driver","LapNumber"])["LapTime"].unique().explode())
Lap_Driver=Lap_Driver.sort_values(by=["Driver","LapTime"])
Lap_Driver["RK"] = Lap_Driver.groupby("Driver")["LapTime"].rank(method="dense", ascending=True)
Lap_Driver.sort_values(by=["LapTime"]).head(10)

                          LapTime   RK
Driver LapNumber
NOR    19         00:01:15.096000  1.0
PIA    17         00:01:15.180000  1.0
NOR    13         00:01:15.415000  2.0
PIA    9          00:01:15.468000  2.0
VER    16         00:01:15.481000  1.0
RUS    20         00:01:15.546000  1.0
NOR    10         00:01:15.556000  3.0
VER    10         00:01:15.565000  2.0
TSU    17         00:01:15.670000  1.0
VER    13         00:01:15.671000  3.0

In [13]:
#Add rank for each lap in the main table to plot easily
track2["LapRank"] = track2.groupby("Driver")["LapTime"].rank(method="dense", ascending=True)

In [18]:
track2[(track2['Driver'].isin(['BOR'])&(track2['LapRank']==1.0))].head()

,Year,GP,Driver,DriverNumber,Team,Position,Status,LapStartTime,LapEndTime,LapInstant,LapTime,LapNumber,RPM,Speed,nGear,Throttle,Brake,DRS,Distance,RelativeDistance,DriverAhead,DistanceToDriverAhead,X,Y,Z,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,TrackStatus,Deleted,DeletedReason,Braking,Dist_Diff2,Dist_Diff,Dist_Diff_Sum,X_Diff,Y_Diff,Z_Diff,Dist,Dist_Total,Dist_Lap,RK,LapRank
149966,2025,Australian Grand Prix,BOR,5,Kick Sauber,<NA>,OnTrack,0 days 00:30:14.883000,0 days 00:31:31.399000,0 days 00:16:58.235000,00:01:16.516000,7,11114.5,313.5,8,100.0,False,12,31441.180717,0.463161,81,4615.851667,-1348.000000,-1189.000000,84.000000,3,NaT,NaT,0 days 00:00:26.495000,0 days 00:00:17.220000,0 days 00:00:32.801000,0 days 00:30:41.378000,0 days 00:30:58.598000,0 days 00:31:31.399000,289,327,306,325,SOFT,2,True,1,False,,0,NaN,NaN,NaN,152100.000000,29584.000000,9.000000,42.625462,683333.092641,42.625462,1,1.0
149967,2025,Australian Grand Prix,BOR,5,Kick Sauber,<NA>,OnTrack,0 days 00:30:14.883000,0 days 00:31:31.399000,0 days 00:16:58.376000,00:01:16.516000,7,11169.0,315.0,8,100.0,False,12,31453.560556,0.463343,81,4604.629444,-1400.617562,-1138.807309,83.480364,3,NaT,NaT,0 days 00:00:26.495000,0 days 00:00:17.220000,0 days 00:00:32.801000,0 days 00:30:41.378000,0 days 00:30:58.598000,0 days 00:31:31.399000,289,327,306,325,SOFT,2,True,1,False,,0,31441.180717,12.379838,12.379838,2768.607794,2519.306260,0.270021,7.271990,683340.364631,49.897452,2,1.0
149968,2025,Australian Grand Prix,BOR,5,Kick Sauber,<NA>,OnTrack,0 days 00:30:14.883000,0 days 00:31:31.399000,0 days 00:16:58.496000,00:01:16.516000,7,11204.0,316.0,8,100.0,False,12,31464.137117,0.463499,81,4597.073889,-1437.000000,-1104.000000,83.000000,3,NaT,NaT,0 days 00:00:26.495000,0 days 00:00:17.220000,0 days 00:00:32.801000,0 days 00:30:41.378000,0 days 00:30:58.598000,0 days 00:31:31.399000,289,327,306,325,SOFT,2,True,1,False,,0,31453.560556,10.576562,22.956400,1323.681820,1211.548739,0.230750,5.035336,683345.399968,54.932788,3,1.0
149969,2025,Australian Grand Prix,BOR,5,Kick Sauber,<NA>,OnTrack,0 days 00:30:14.883000,0 days 00:31:31.399000,0 days 00:16:58.736000,00:01:16.516000,7,11239.0,317.0,8,100.0,False,12,31485.359288,0.463811,81,4589.518333,-1589.000000,-959.000000,82.000000,3,NaT,NaT,0 days 00:00:26.495000,0 days 00:00:17.220000,0 days 00:00:32.801000,0 days 00:30:41.378000,0 days 00:30:58.598000,0 days 00:31:31.399000,289,327,306,325,SOFT,2,True,1,False,,0,31464.137117,21.222171,44.178571,23104.000000,21025.000000,1.000000,21.007142,683366.407109,75.939930,4,1.0
149970,2025,Australian Grand Prix,BOR,5,Kick Sauber,<NA>,OnTrack,0 days 00:30:14.883000,0 days 00:31:31.399000,0 days 00:16:58.776000,00:01:16.516000,7,11274.0,318.0,8,100.0,False,12,31488.893889,0.463863,81,4581.962778,-1615.786115,-933.422780,81.849081,3,NaT,NaT,0 days 00:00:26.495000,0 days 00:00:17.220000,0 days 00:00:32.801000,0 days 00:30:41.378000,0 days 00:30:58.598000,0 days 00:31:31.399000,289,327,306,325,SOFT,2,True,1,False,,0,31485.359288,3.534601,47.713172,717.495934,654.194163,0.022777,3.703664,683370.110773,79.643594,5,1.0

In [17]:
track2[(track2['Driver'].isin(['LEC'])&(track2['LapRank']==1.0))].head()

,Year,GP,Driver,DriverNumber,Team,Position,Status,LapStartTime,LapEndTime,LapInstant,LapTime,LapNumber,RPM,Speed,nGear,Throttle,Brake,DRS,Distance,RelativeDistance,DriverAhead,DistanceToDriverAhead,X,Y,Z,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,TrackStatus,Deleted,DeletedReason,Braking,Dist_Diff2,Dist_Diff,Dist_Diff_Sum,X_Diff,Y_Diff,Z_Diff,Dist,Dist_Total,Dist_Lap,RK,LapRank
351397,2025,Australian Grand Prix,LEC,16,Ferrari,<NA>,OnTrack,0 days 01:02:36.229000,0 days 01:03:51.984000,0 days 00:48:03.753000,00:01:15.755000,17,11179.5,313.5,8,100.0,False,12,83710.087979,0.802074,44,9565.204167,-1255.000000,-1277.000000,84.000000,7,NaT,NaT,0 days 00:00:26.194000,0 days 00:00:17.025000,0 days 00:00:32.536000,0 days 01:03:02.423000,0 days 01:03:19.448000,0 days 01:03:51.984000,290,325,309,326,SOFT,2,True,1,False,,0,NaN,NaN,NaN,92416.000000,8100.000000,4.000000,31.704889,1.387998e+06,31.704889,1,1.0
351398,2025,Australian Grand Prix,LEC,16,Ferrari,<NA>,OnTrack,0 days 01:02:36.229000,0 days 01:03:51.984000,0 days 00:48:03.826000,00:01:15.755000,17,11240.0,316.0,8,100.0,False,12,83716.522222,0.802136,44,9560.448611,-1315.401397,-1219.664597,83.645748,7,NaT,NaT,0 days 00:00:26.194000,0 days 00:00:17.025000,0 days 00:00:32.536000,0 days 01:03:02.423000,0 days 01:03:19.448000,0 days 01:03:51.984000,290,325,309,326,SOFT,2,True,1,False,,0,83710.087979,6.434243,6.434243,3648.328706,3287.348465,0.125495,8.328147,1.388006e+06,40.033036,2,1.0
351399,2025,Australian Grand Prix,LEC,16,Ferrari,<NA>,OnTrack,0 days 01:02:36.229000,0 days 01:03:51.984000,0 days 00:48:03.954000,00:01:15.755000,17,11271.5,317.0,8,100.0,False,12,83727.821401,0.802244,44,9556.681944,-1434.000000,-1107.000000,83.000000,7,NaT,NaT,0 days 00:00:26.194000,0 days 00:00:17.025000,0 days 00:00:32.536000,0 days 01:03:02.423000,0 days 01:03:19.448000,0 days 01:03:51.984000,290,325,309,326,SOFT,2,True,1,False,,0,83716.522222,11.299178,17.733421,14065.628738,12693.311363,0.416990,16.358288,1.388023e+06,56.391323,3,1.0
351400,2025,Australian Grand Prix,LEC,16,Ferrari,<NA>,OnTrack,0 days 01:02:36.229000,0 days 01:03:51.984000,0 days 00:48:04.066000,00:01:15.755000,17,11303.0,318.0,8,100.0,False,12,83737.722222,0.802339,44,9552.915278,-1510.244394,-1034.431969,82.773385,7,NaT,NaT,0 days 00:00:26.194000,0 days 00:00:17.025000,0 days 00:00:32.536000,0 days 01:03:02.423000,0 days 01:03:19.448000,0 days 01:03:51.984000,290,325,309,326,SOFT,2,True,1,False,,0,83727.821401,9.900822,27.634243,5813.207548,5266.119116,0.051354,10.525862,1.388033e+06,66.917186,4,1.0
351401,2025,Australian Grand Prix,LEC,16,Ferrari,<NA>,OnTrack,0 days 01:02:36.229000,0 days 01:03:51.984000,0 days 00:48:04.306000,00:01:15.755000,17,11337.0,319.0,8,100.0,False,12,83758.988889,0.802543,44,9544.781944,-1614.885224,-934.442108,82.545968,7,NaT,NaT,0 days 00:00:26.194000,0 days 00:00:17.025000,0 days 00:00:32.536000,0 days 01:03:02.423000,0 days 01:03:19.448000,0 days 01:03:51.984000,290,325,309,326,SOFT,2,True,1,False,,0,83737.722222,21.266667,48.900909,10949.703351,9997.972292,0.051718,14.473330,1.388048e+06,81.390516,5,1.0

In [75]:
fig_speed=px.line(data_frame=track2[(track2['Driver'].isin(['HAM'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="Speed",
           color="Driver", hover_name="Driver",
           height=900, width=1500,
               template="plotly_dark",
           title="Speed Trace For Leclerc vs. Hamilton's Fastest Qualifying Laps (2025 Australian GP Qualifying)",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "GAS": "#0093cc",
                 "HAM": "#FFDE00",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
          }
          )
# fig_speed.add_layout_image(
#     dict(
#         source=Image.open("/content/images.jpg"),
#         xref="x", yref="y",
#         x=4500, y=300,
#         sizex=500, sizey=500,
#         xanchor="left", yanchor="middle"
#     )
# )
fig_speed.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Speed (Km/Hr)",
)

fig_speed.update_layout(
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    hoverlabel=dict(
        bgcolor="white",
        font_size=20,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=24,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)
fig_speed.show()

In [76]:
fig_speed_addtl=px.line(track2[(track2['Driver'].isin(['LEC'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="Speed",
           color="Driver", hover_name="Driver",
           height=900, width=1800,
           template="presentation",
           title="Speed Trace For Leclerc vs. Hamilton's Fastest Qualifying Laps (2025 Australian GP Qualifying)",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "GAS": "#0093cc",
                 "HAM": "#FFDE00",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
          }
          )

fig_speed.add_traces(
    list(fig_speed_addtl.select_traces())
)

fig_speed.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Speed (Km/Hr)",
)
fig_speed.update_layout(
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=24,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_speed.show()

In [77]:
#Speed Trace with Corner Markings

In [78]:
v_min = track2['Speed'].min()
v_max = track2['Speed'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_speed.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min+25,
                x1=k,
                y1=v_max+5,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_speed.update_xaxes(range=[0, 5000])
fig_speed.update_yaxes(range=[10, 350])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_speed.add_annotation(x=corner['Distance'], y=v_max, text=txt, showarrow=False, yshift=10)

fig_speed.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=20,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_speed.show()

In [33]:
fig_throttle=px.line(data_frame=track2[(track2['Driver'].isin(['HAM','VER','LEC'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="Throttle",
           color="Driver", hover_name="Driver",
           height=900, width=1800,
           template="plotly_dark",
           title="Throttle Trace For GP",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
          }
          )

fig_throttle.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="DRS",
)

v_min = track2['Throttle'].min()
v_max = track2['Throttle'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_throttle.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min-5,
                x1=k,
                y1=v_max+20,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_throttle.update_xaxes(range=[0, 5000])
fig_throttle.update_yaxes(range=[-10, 110])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_throttle.add_annotation(x=corner['Distance'], y=v_min-7, text=txt, showarrow=False, yshift=10)

fig_throttle.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_throttle.show()

In [18]:
fig_brake=px.line(data_frame=track2[(track2['Driver'].isin(['HAM','VER','LEC'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="Braking",
           color="Driver", hover_name="Driver",
           height=900, width=1800,
           template="plotly_dark",
           title="Brake Trace For GP",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
          }
          )

fig_brake.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Brakes",
)

v_min = track2['Braking'].min()
v_max = track2['Braking'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_brake.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min-0.25,
                x1=k,
                y1=v_max+0.2,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_brake.update_xaxes(range=[0, 5000])
fig_brake.update_yaxes(range=[-0.5, 1.2])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_brake.add_annotation(x=corner['Distance'], y=v_min-0.3, text=txt, showarrow=False, yshift=10)

fig_brake.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_brake.show()

In [19]:
fig_drs=px.line(data_frame=track2[(track2['Driver'].isin(['HAM','VER','LEC'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="DRS",
           color="Driver", hover_name="Driver",
           height=900, width=1800,
           template="plotly_dark",
           title="DRS Trace For GP",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
          }
          )

fig_drs.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="DRS",
)

v_min = track2['DRS'].min()
v_max = track2['DRS'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_drs.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min-5,
                x1=k,
                y1=v_max+2,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_drs.update_xaxes(range=[0, 5000])
fig_drs.update_yaxes(range=[-0.5, 18])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_drs.add_annotation(x=corner['Distance'], y=v_min-5.5, text=txt, showarrow=False, yshift=10)
fig_drs.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)
fig_drs.show()

In [20]:
#Plot as a subplot
import plotly.express as px
import plotly.subplots as sp


# For as many traces that exist per Express figure, get the
# traces from each plot and store them in an array.
# This is essentially breaking down the Express fig into it's traces
figure1_traces = []
figure2_traces = []
figure3_traces = []
figure4_traces = []

for trace in range(len(fig_speed["data"])):
    figure1_traces.append(fig_speed["data"][trace])
for trace in range(len(fig_throttle["data"])):
    figure2_traces.append(fig_throttle["data"][trace])
for trace in range(len(fig_brake["data"])):
    figure3_traces.append(fig_brake["data"][trace])
for trace in range(len(fig_drs["data"])):
    figure4_traces.append(fig_drs["data"][trace])

this_figure = sp.make_subplots(rows=4, cols=1)

for traces in figure1_traces:
    this_figure.append_trace(traces, row=1, col=1)
for traces in figure2_traces:
    this_figure.append_trace(traces, row=2, col=1)
for traces in figure3_traces:
    this_figure.append_trace(traces, row=3, col=1)
for traces in figure4_traces:
    this_figure.append_trace(traces, row=4, col=1)

this_figure.update_layout(height=1800, width=1800, title_text="Lap Traces")

this_figure.update_layout(
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)
this_figure.show()