In [3]:
import pandas as pd
import numpy as np
import itertools
import datetime
import matplotlib.pyplot as plt
import pandas_gbq
from PIL import Image
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
import fastf1
session = fastf1.get_session(2025, 'Chinese Grand Prix', 'SQ')
session.load()

circuit_info = session.get_circuit_info()

req         WARNING 	DEFAULT CACHE ENABLED! (6.51 GB) /Users/rdesh723/Library/Caches/fastf1
core           INFO 	Loading data for Chinese Grand Prix - Sprint Qualifying [v3.5.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	Sprint Qualifying is not supported by Ergast! Limited results are calculated from timing data.
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '81', '16', '63', '4', '12', '22', '23', '18', '14', '87', '55', '5', '6', '7', '10', '31', '27', '30']

In [4]:
query2=f"""
SELECT
A.Year,
A.GP,
A.Driver,
A.DriverNumber,
A.Team,
CAST(A.Position AS INT64) Position,
Status,
A.LapStartTime,
A.Time LapEndTime,
B.Time as LapInstant,
A.LapTime,
CAST(LapNumber as INT64) LapNumber,
RPM,
Speed,
nGear,
Throttle,
Brake,
DRS,
Distance,
RelativeDistance,
DriverAhead,
DistanceToDriverAhead,
X,
Y,
Z,
CAST(Stint as INT64) Stint,
PitOutTime,
PitInTime,
Sector1Time,
Sector2Time,
Sector3Time,
Sector1SessionTime,
Sector2SessionTime,
Sector3SessionTime,
CAST(SpeedI1 AS INT64) SpeedI1,
CAST(SpeedI2 AS INT64) SpeedI2,
CAST(SpeedFL AS INT64) SpeedFL,
CAST(SpeedST AS INT64) SpeedST,
Compound,
CAST(TyreLife AS INT64) TyreLife,
FreshTyre,
TrackStatus,
Deleted,
DeletedReason
FROM `perceptive-ivy-290216.f1_api.qualifying_lap_time`  A
INNER JOIN
`perceptive-ivy-290216.f1_api.qualifying_telemetry_2025` B
ON B.SessionTime>=A.LapStartTime AND B.SessionTime<=A.Time
AND A.Driver=B.Driver
AND A.Year=B.Year
AND A.GP=B.GP
WHERE A.Year=2025
AND A.GP="Australian Grand Prix"
# AND A.DRIVER='HAM'
AND B.Year=2025
AND B.GP="Australian Grand Prix"
# AND B.Driver='HAM'
ORDER BY LapNumber, LapStartTime, LapInstant
"""
track1=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [8]:
query2=f"""
SELECT
A.Year,
A.GP,
A.Driver,
A.DriverNumber,
A.Team,
CAST(A.Position AS INT64) Position,
Status,
A.LapStartTime,
A.Time LapEndTime,
B.Time as LapInstant,
A.LapTime,
CAST(LapNumber as INT64) LapNumber,
RPM,
Speed,
nGear,
Throttle,
Brake,
DRS,
Distance,
RelativeDistance,
DriverAhead,
DistanceToDriverAhead,
X,
Y,
Z,
CAST(Stint as INT64) Stint,
PitOutTime,
PitInTime,
Sector1Time,
Sector2Time,
Sector3Time,
Sector1SessionTime,
Sector2SessionTime,
Sector3SessionTime,
CAST(SpeedI1 AS INT64) SpeedI1,
CAST(SpeedI2 AS INT64) SpeedI2,
CAST(SpeedFL AS INT64) SpeedFL,
CAST(SpeedST AS INT64) SpeedST,
Compound,
CAST(TyreLife AS INT64) TyreLife,
FreshTyre,
TrackStatus,
Deleted,
DeletedReason
FROM `perceptive-ivy-290216.f1_api.sprint_qualifying_lap_time`  A
INNER JOIN
`perceptive-ivy-290216.f1_api.sprint_qualifying_telemetry_2025` B
ON B.SessionTime>=A.LapStartTime AND B.SessionTime<=A.Time
AND A.Driver=B.Driver
AND A.Year=B.Year
AND A.GP=B.GP
WHERE A.Year=2025
AND A.GP="Chinese Grand Prix"
# AND A.DRIVER='HAM'
AND B.Year=2025
AND B.GP="Chinese Grand Prix"
# AND B.Driver='HAM'
ORDER BY LapNumber, LapStartTime, LapInstant
"""
track1=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [9]:
track2=track1.copy()
year=track2['Year'][0]
gp=track2['GP'][0]

In [10]:
#Convert braking from True False to 0 & 1
def braking_ind(ind):
  if ind==True:
    return 1
  else:
    return 0

track2['Braking'] = track2['Brake'].apply(braking_ind)

In [11]:
track2["LapTime"]=track2['LapTime'].str.split('days ').str[1]
track2["LapTime"]=pd.to_datetime(track2['LapTime'],format='%H:%M:%S.%f')
track2["LapTime"]=track2["LapTime"].dt.strftime("%H:%M:%S.%f")

In [12]:
#Convert lapnumber to string for discrete chart coloring
track2["LapNumber"]=track2["LapNumber"].astype(str)

In [13]:
track2['Dist_Diff2'] = track2.groupby(["LapNumber","Driver"])["Distance"].shift(1)
# track2['Dist_Diff2'] = track2.groupby(["Driver"])["Distance"].shift(1) ## Use when not looking at just 1 lap
track2['Dist_Diff'] = track2['Distance']-track2["Dist_Diff2"]
track2["Dist_Diff_Sum"] = track2.groupby(by=["LapNumber","Driver"])["Dist_Diff"].cumsum()
# track2["Dist_Diff_Sum"] = track2.groupby(by=["Driver"])["Dist_Diff"].cumsum()  ## Use when not looking at just 1 lap

##Another way to calculate distances manually, if the distance column wasnt present in the data set. Dist_Diff_Sum AND Dist_Total Should match very closely which they do, even when using our own method

#Calculate the distance traversed in totality and then for each lap
track2['X_Diff'] = track2['X'] - track2['X'].shift(1)
track2['Y_Diff'] = track2['Y'] - track2['Y'].shift(1)
track2['Z_Diff'] = track2['Z'] - track2['Z'].shift(1)
track2['X_Diff']=track2['X_Diff'].pow(2)
track2['Y_Diff']=track2['Y_Diff'].pow(2)
track2['Z_Diff']=track2['Z_Diff'].pow(2)
track2['Dist']=track2['X_Diff']+track2['Y_Diff']+track2['Z_Diff']

#Distance between current point and previous data point
track2['Dist']=track2['Dist'].pow(1./2)
track2['Dist']=track2['Dist']/10

#Running sum of distance covered by a driver
track2['Dist_Total']=track2['Dist'].cumsum()

#Running sum of distance covered by a driver by lap
track2["Dist_Lap"] = track2.groupby(by=["LapNumber","Driver"])["Dist"].cumsum()

# #Drop columns that are not necessary anymore
# track2.drop(['X_Diff','Y_Diff','Z_Diff','Dist_Diff2'], axis=1, inplace=True)

# #Assign Rank for each entry point
track2["RK"] = track2.groupby(by=["LapNumber","Driver"])["LapInstant"].rank(method="dense", ascending=True)
track2["RK"]= track2["RK"].astype(int)
track2=track2.sort_values(by=['Driver','LapInstant'])

In [14]:
# track2[(track2["Driver"]=='HAM')&((track2["LapNumber"]=='1')|(track2["LapNumber"]=='2'))].sort_values(by=["LapNumber","LapInstant"])

In [15]:
# pd.DataFrame(track2.groupby(by=["Driver"])["LapTime"].unique())
Lap_Driver=pd.DataFrame(track2.groupby(by=["Driver","LapNumber"])["LapTime"].unique().explode())
Lap_Driver=Lap_Driver.sort_values(by=["Driver","LapTime"])
Lap_Driver["RK"] = Lap_Driver.groupby("Driver")["LapTime"].rank(method="dense", ascending=True)
Lap_Driver.sort_values(by=["LapTime"]).head(10)

                          LapTime   RK
Driver LapNumber
HAM    14         00:01:30.849000  1.0
VER    11         00:01:30.867000  1.0
PIA    10         00:01:30.929000  1.0
       12         00:01:30.940000  2.0
LEC    14         00:01:31.057000  1.0
RUS    17         00:01:31.169000  1.0
NOR    8          00:01:31.174000  1.0
HAM    5          00:01:31.212000  2.0
RUS    14         00:01:31.346000  2.0
PIA    7          00:01:31.362000  3.0

In [23]:
#Add rank for each lap in the main table to plot easily
track2["LapRank"] = track2.groupby("Driver")["LapTime"].rank(method="dense", ascending=True)

In [24]:
track2[(track2['Driver'].isin(['HAM'])&(track2['LapRank']==1.0))].head()

,Year,GP,Driver,DriverNumber,Team,Position,Status,LapStartTime,LapEndTime,LapInstant,LapTime,LapNumber,RPM,Speed,nGear,Throttle,Brake,DRS,Distance,RelativeDistance,DriverAhead,DistanceToDriverAhead,X,Y,Z,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,TrackStatus,Deleted,DeletedReason,Braking,Dist_Diff2,Dist_Diff,Dist_Diff_Sum,X_Diff,Y_Diff,Z_Diff,Dist,Dist_Total,Dist_Lap,RK,LapRank
275579,2025,Chinese Grand Prix,HAM,44,Ferrari,<NA>,OnTrack,0 days 00:53:59.988000,0 days 00:55:30.837000,0 days 00:39:54.927000,00:01:30.849000,14,11064.5,276.0,7,100.0,False,12,69938.688923,0.865841,12,20135.624722,202.000000,-1460.000000,140.000000,4,NaT,NaT,0 days 00:00:24.261000,0 days 00:00:27.249000,0 days 00:00:39.339000,0 days 00:54:24.249000,0 days 00:54:51.498000,0 days 00:55:30.837000,283,278,270,335,SOFT,2,True,1,False,,0,NaN,NaN,NaN,33814.954971,19318.050607,361.000000,23.128771,1.109202e+06,23.128771,1,1.0
275580,2025,Chinese Grand Prix,HAM,44,Ferrari,<NA>,OnTrack,0 days 00:53:59.988000,0 days 00:55:30.837000,0 days 00:39:55.008000,00:01:30.849000,14,11138.0,278.0,7,100.0,False,12,69944.968056,0.865919,12,20135.901111,147.349390,-1473.231325,139.965232,4,NaT,NaT,0 days 00:00:24.261000,0 days 00:00:27.249000,0 days 00:00:39.339000,0 days 00:54:24.249000,0 days 00:54:51.498000,0 days 00:55:30.837000,283,278,270,335,SOFT,2,True,1,False,,0,69938.688923,6.279133,6.279133,2986.689128,175.067973,0.001209,5.622951,1.109207e+06,28.751723,2,1.0
275581,2025,Chinese Grand Prix,HAM,44,Ferrari,<NA>,OnTrack,0 days 00:53:59.988000,0 days 00:55:30.837000,0 days 00:39:55.108000,00:01:30.849000,14,11207.5,280.0,7,99.5,False,12,69952.764408,0.866015,12,20136.213333,75.000000,-1491.000000,140.000000,4,NaT,NaT,0 days 00:00:24.261000,0 days 00:00:27.249000,0 days 00:00:39.339000,0 days 00:54:24.249000,0 days 00:54:51.498000,0 days 00:55:30.837000,283,278,270,335,SOFT,2,True,1,False,,0,69944.968056,7.796353,14.075486,5234.434293,315.725796,0.001209,7.449940,1.109215e+06,36.201663,3,1.0
275582,2025,Chinese Grand Prix,HAM,44,Ferrari,<NA>,OnTrack,0 days 00:53:59.988000,0 days 00:55:30.837000,0 days 00:39:55.289000,00:01:30.849000,14,11277.0,282.0,7,99.0,False,12,69966.979722,0.866191,12,20136.525556,-99.891969,-1535.170435,139.511441,4,NaT,NaT,0 days 00:00:24.261000,0 days 00:00:27.249000,0 days 00:00:39.339000,0 days 00:54:24.249000,0 days 00:54:51.498000,0 days 00:55:30.837000,283,278,270,335,SOFT,2,True,1,False,,0,69952.764408,14.215314,28.290800,30587.200771,1951.027339,0.238690,18.038422,1.109233e+06,54.240085,4,1.0
275583,2025,Chinese Grand Prix,HAM,44,Ferrari,<NA>,OnTrack,0 days 00:53:59.988000,0 days 00:55:30.837000,0 days 00:39:55.487000,00:01:30.849000,14,11347.0,283.5,7,99.0,False,12,69982.640044,0.866385,12,20136.758889,-285.000000,-1582.000000,139.000000,4,NaT,NaT,0 days 00:00:24.261000,0 days 00:00:27.249000,0 days 00:00:39.339000,0 days 00:54:24.249000,0 days 00:54:51.498000,0 days 00:55:30.837000,283,278,270,335,SOFT,2,True,1,False,,0,69966.979722,15.660322,43.951122,34264.983193,2193.008146,0.261571,19.094044,1.109252e+06,73.334129,5,1.0

In [31]:
track2[(track2['Driver'].isin(['VER'])&(track2['LapRank']==1.0))].head()

,Year,GP,Driver,DriverNumber,Team,Position,Status,LapStartTime,LapEndTime,LapInstant,LapTime,LapNumber,RPM,Speed,nGear,Throttle,Brake,DRS,Distance,RelativeDistance,DriverAhead,DistanceToDriverAhead,X,Y,Z,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,TrackStatus,Deleted,DeletedReason,Braking,Dist_Diff2,Dist_Diff,Dist_Diff_Sum,X_Diff,Y_Diff,Z_Diff,Dist,Dist_Total,Dist_Lap,RK,LapRank
249187,2025,Chinese Grand Prix,VER,1,Red Bull Racing,<NA>,OnTrack,0 days 00:55:26.460000,0 days 00:56:57.327000,0 days 00:42:25.511000,00:01:30.867000,11,11054.0,278.0,7,100.0,False,12,53811.379114,0.832881,18,2999.334722,78.000000,-1490.000000,140.000000,4,NaT,NaT,0 days 00:00:24.269000,0 days 00:00:27.361000,0 days 00:00:39.237000,0 days 00:55:50.729000,0 days 00:56:18.090000,0 days 00:56:57.327000,281,275,269,336,SOFT,2,True,1,False,,0,NaN,NaN,NaN,12376.421033,727.547987,0.007693,11.447260,989959.956263,11.447260,1,1.0
249188,2025,Chinese Grand Prix,VER,1,Red Bull Racing,<NA>,OnTrack,0 days 00:55:26.460000,0 days 00:56:57.327000,0 days 00:42:25.514000,00:01:30.867000,11,11125.0,280.0,7,100.0,False,12,53811.615000,0.832885,18,2994.234722,74.920280,-1490.782381,140.001292,4,NaT,NaT,0 days 00:00:24.269000,0 days 00:00:27.361000,0 days 00:00:39.237000,0 days 00:55:50.729000,0 days 00:56:18.090000,0 days 00:56:57.327000,281,275,269,336,SOFT,2,True,1,False,,0,53811.379114,0.235886,0.235886,9.484675,0.612120,0.000002,0.317755,989960.274017,11.765015,2,1.0
249189,2025,Chinese Grand Prix,VER,1,Red Bull Racing,<NA>,OnTrack,0 days 00:55:26.460000,0 days 00:56:57.327000,0 days 00:42:25.731000,00:01:30.867000,11,11234.0,283.0,7,100.0,False,12,53828.787628,0.833151,18,2984.090278,-170.000000,-1554.000000,140.000000,4,NaT,NaT,0 days 00:00:24.269000,0 days 00:00:27.361000,0 days 00:00:39.237000,0 days 00:55:50.729000,0 days 00:56:18.090000,0 days 00:56:57.327000,281,275,269,336,SOFT,2,True,1,False,,0,53811.615000,17.172628,17.408514,59985.943601,3996.467376,0.000002,25.294745,989985.568762,37.059760,3,1.0
249190,2025,Chinese Grand Prix,VER,1,Red Bull Racing,<NA>,OnTrack,0 days 00:55:26.460000,0 days 00:56:57.327000,0 days 00:42:25.954000,00:01:30.867000,11,11343.0,286.0,7,100.0,False,12,53846.570556,0.833426,18,2973.945833,-249.145333,-1573.640170,139.062295,4,NaT,NaT,0 days 00:00:24.269000,0 days 00:00:27.361000,0 days 00:00:39.237000,0 days 00:55:50.729000,0 days 00:56:18.090000,0 days 00:56:57.327000,281,275,269,336,SOFT,2,True,1,False,,0,53828.787628,17.782928,35.191442,6263.983682,385.736266,0.879290,8.155121,989993.723883,45.214880,4,1.0
249191,2025,Chinese Grand Prix,VER,1,Red Bull Racing,<NA>,OnTrack,0 days 00:55:26.460000,0 days 00:56:57.327000,0 days 00:42:25.972000,00:01:30.867000,11,11376.5,287.0,7,100.0,False,12,53848.007762,0.833448,18,2970.168056,-259.000000,-1576.000000,139.000000,4,NaT,NaT,0 days 00:00:24.269000,0 days 00:00:27.361000,0 days 00:00:39.237000,0 days 00:55:50.729000,0 days 00:56:18.090000,0 days 00:56:57.327000,281,275,269,336,SOFT,2,True,1,False,,0,53846.570556,1.437207,36.628649,97.114468,5.568799,0.003881,1.013347,989994.737229,46.228227,5,1.0

In [148]:
from fastf1 import utils

session = fastf1.get_session(2025, 'Chinese Grand Prix', 'SQ')
session.load()
ver = session.laps.pick_drivers('VER').pick_fastest()
ham = session.laps.pick_drivers('HAM').pick_fastest()


delta_time, ref_tel, compare_tel = utils.delta_time(ham, ver)
delta_time=pd.DataFrame(delta_time)
delta_time=delta_time.reset_index()
delta_time.columns=["RK", "Delta"]

compare_tel=compare_tel.reset_index()
compare_tel.columns=["RK", 'Date', 'SessionTime', 'RPM', 'Speed', 'nGear', 'Throttle', 'Brake',
       'DRS', 'Source', 'Time', 'Distance']
compare_tel=compare_tel.merge(delta_time, left_on="RK", right_on="RK")

core           INFO 	Loading data for Chinese Grand Prix - Sprint Qualifying [v3.5.0]

req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	Sprint Qualifying is not supported by Ergast! Limited results are calculated from timing data.
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '81', '16', '63', '4', '12', '22', '23', '18', '14', '87', '55', '5', '6', '7', '10', '31', '27', '30']
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastf1/utils.py:89: FutureWarning:

`utils.delta_time` is considered deprecated and willbe modified or removed in a future release because it hasa tendency to give inaccurate results.

In [160]:
v_min = compare_tel['Delta'].min()
v_max = compare_tel['Delta'].max()
corner_distance=circuit_info.corners['Distance']

fig_delta=px.line(data_frame=compare_tel, x="Distance", y="Delta",
           height=450, width=1500,
               template="plotly_dark",
               title="Time Delta Between HAM and VER Fastest Laps (2025 Chinese GP Sprint Qualifying)"
          )
# fig_speed.add_layout_image(
#     dict(
#         source=Image.open("/content/images.jpg"),
#         xref="x", yref="y",
#         x=4500, y=300,
#         sizex=500, sizey=500,
#         xanchor="left", yanchor="middle"
#     )
# )
fig_delta.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Delta (s)",
)

for k in corner_distance:
  fig_delta.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min,
                x1=k,
                y1=v_max,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_delta.update_xaxes(range=[0, 5400])
fig_delta.update_yaxes(range=[-0.2, 0.5])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_delta.add_annotation(x=corner['Distance'], y=v_max, text=txt, showarrow=False, yshift=10)

fig_delta.update_layout(
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    hoverlabel=dict(
        bgcolor="white",
        font_size=15,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=18,
        color="White"
    ),
    title_font_family="PT Sans Narrow"

)

fig_delta.update_traces(line_color='White', line_width=2)

fig_delta.show()

In [ ]:
session = fastf1.get_session(2025, 'Chinese Grand Prix', 'SQ')
session.load()
ver_lap = session.laps.pick_drivers('VER').pick_fastest()
ham_lap = session.laps.pick_drivers('HAM').pick_fastest()
ver_tel = ver_lap.get_car_data().add_distance()
ham_tel = ham_lap.get_car_data().add_distance()

In [170]:
fig_speed=px.line(data_frame=track2[(track2['Driver'].isin(['HAM'])&(track2['LapRank']==1.0))], x="Dist_Lap", y="Speed",
           color="Driver", hover_name="Driver",
           height=450, width=1500,
               template="plotly_dark",
           title="Speed Trace For Hamilton vs. Verstappen's Fastest Qualifying Laps (2025 Chinese GP Sprint Qualifying)",
           color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
          )
# fig_speed.add_layout_image(
#     dict(
#         source=Image.open("/content/images.jpg"),
#         xref="x", yref="y",
#         x=4500, y=300,
#         sizex=500, sizey=500,
#         xanchor="left", yanchor="middle"
#     )
# )
fig_speed.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Speed (Km/Hr)",
)

fig_speed.update_layout(
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    hoverlabel=dict(
        bgcolor="white",
        font_size=20,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=24,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)
fig_speed.show()

In [171]:
fig_speed_addtl=px.line(track2[(track2['Driver'].isin(['VER'])&(track2['LapRank']==1.0))], x="Dist_Lap", y="Speed",
           color="Driver", hover_name="Driver",
           height=450, width=1800,
           template="presentation",
           title="Speed Trace For Leclerc vs. Hamilton's Fastest Qualifying Laps (2025 Australian GP Qualifying)",
           color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
          )

fig_speed.add_traces(
    list(fig_speed_addtl.select_traces())
)

fig_speed.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Speed (Km/Hr)",
)
fig_speed.update_layout(
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=24,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_speed.show()

In [163]:
#Speed Trace with Corner Markings

In [165]:
v_min = track2['Speed'].min()
v_max = track2['Speed'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_speed.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min+25,
                x1=k,
                y1=v_max+5,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_speed.update_xaxes(range=[0, 5400])
fig_speed.update_yaxes(range=[10, 350])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_speed.add_annotation(x=corner['Distance'], y=v_max, text=txt, showarrow=False, yshift=10)

fig_speed.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=18,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_speed.show()

In [53]:
fig_throttle=px.line(data_frame=track2[(track2['Driver'].isin(['HAM','VER'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="Throttle",
           color="Driver", hover_name="Driver",
           height=900, width=1500,
           template="plotly_dark",
           title="Throttle Trace For GP",
           color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
          )

fig_throttle.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Throttle (%)",
)

v_min = track2['Throttle'].min()
v_max = track2['Throttle'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_throttle.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min-5,
                x1=k,
                y1=v_max+20,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_throttle.update_xaxes(range=[0, 5000])
fig_throttle.update_yaxes(range=[-10, 115])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_throttle.add_annotation(x=corner['Distance'], y=v_max+10, text=txt, showarrow=False, yshift=10)

fig_throttle.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=18,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_throttle.show()

In [54]:
fig_brake=px.line(data_frame=track2[(track2['Driver'].isin(['HAM','VER'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="Braking",
           color="Driver", hover_name="Driver",
           height=900, width=1500,
           template="plotly_dark",
           title="Brake Trace For GP",
           color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
          )

fig_brake.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="Brakes",
)

v_min = track2['Braking'].min()
v_max = track2['Braking'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_brake.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min-0.25,
                x1=k,
                y1=v_max+0.2,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_brake.update_xaxes(range=[0, 5000])
fig_brake.update_yaxes(range=[-0.5, 1.5])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_brake.add_annotation(x=corner['Distance'], y=v_max+0.2, text=txt, showarrow=False, yshift=10)

fig_brake.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=18,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)

fig_brake.show()

In [55]:
fig_drs=px.line(data_frame=track2[(track2['Driver'].isin(['HAM','VER'])&(track2['LapRank']==1.0))], x="Dist_Diff_Sum", y="DRS",
           color="Driver", hover_name="Driver",
           height=900, width=1500,
           template="plotly_dark",
           title="DRS Trace For GP",
           color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
          )

fig_drs.update_layout(
    xaxis_title="Distance (m)",
    yaxis_title="DRS",
)

v_min = track2['DRS'].min()
v_max = track2['DRS'].max()
corner_distance=circuit_info.corners['Distance']

for k in corner_distance:
  fig_drs.add_shape(type='line',
                yref="y",
                xref="x",
                x0=k,
                y0=v_min-5,
                x1=k,
                y1=v_max+2,
                line_width=1,
                line_dash="dash",
                line_color="grey")
fig_drs.update_xaxes(range=[0, 5000])
fig_drs.update_yaxes(range=[-0.5, 18])

for _, corner in circuit_info.corners.iterrows():
    txt = f"{corner['Number']}{corner['Letter']}"
    fig_drs.add_annotation(x=corner['Distance'], y=v_min-5.5, text=txt, showarrow=False, yshift=10)
fig_drs.update_layout(
   title_x=0.5,
   hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=18,
        color="White"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)
fig_drs.show()

In [40]:
#Plot as a subplot
import plotly.express as px
import plotly.subplots as sp


# For as many traces that exist per Express figure, get the
# traces from each plot and store them in an array.
# This is essentially breaking down the Express fig into it's traces
figure1_traces = []
figure2_traces = []
figure3_traces = []
figure4_traces = []

for trace in range(len(fig_speed["data"])):
    figure1_traces.append(fig_speed["data"][trace])
for trace in range(len(fig_throttle["data"])):
    figure2_traces.append(fig_throttle["data"][trace])
for trace in range(len(fig_brake["data"])):
    figure3_traces.append(fig_brake["data"][trace])
for trace in range(len(fig_drs["data"])):
    figure4_traces.append(fig_drs["data"][trace])

this_figure = sp.make_subplots(rows=4, cols=1)

for traces in figure1_traces:
    this_figure.append_trace(traces, row=1, col=1)
for traces in figure2_traces:
    this_figure.append_trace(traces, row=2, col=1)
for traces in figure3_traces:
    this_figure.append_trace(traces, row=3, col=1)
for traces in figure4_traces:
    this_figure.append_trace(traces, row=4, col=1)

this_figure.update_layout(height=1800, width=1800, title_text="Lap Traces")

this_figure.update_layout(
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
#  "Arial", "Balto", "Courier New", "Droid Sans", "Droid Serif", "Droid Sans Mono", "Gravitas One", "Old Standard TT", "Open Sans", "Overpass", "PT Sans Narrow", "Raleway", "Times New Roman"
)
this_figure.show()