In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
#Sprint Race Results

In [4]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_sprint`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [5]:
GP=df_bq2
GP=GP.fillna(0)
GP["Position"]=GP["Position"].astype(int)
GP["GridPosition"]=GP["GridPosition"].astype(int)
GP["Points"]=GP["Points"].astype(int)
GP=GP[GP["Position"]!=0]
GP.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
0,10,P GASLY,GAS,gasly,Alpine,0093cc,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,FRA,9,9,8,NaT,NaT,NaT,0 days 00:00:14.513000,Finished,0,2024,Qatar Grand Prix
1,31,E OCON,OCO,ocon,Alpine,0093cc,alpine,Esteban,Ocon,Esteban Ocon,https://media.formula1.com/d_driver_fallback_i...,FRA,14,14,17,NaT,NaT,NaT,0 days 00:00:30.379000,Finished,0,2024,Qatar Grand Prix
2,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,ESP,11,11,11,NaT,NaT,NaT,0 days 00:00:19.204000,Finished,0,2024,Qatar Grand Prix
3,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,CAN,13,13,14,NaT,NaT,NaT,0 days 00:00:24.421000,Finished,0,2024,Qatar Grand Prix
4,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,GBR,3,3,2,NaT,NaT,NaT,0 days 00:00:00.410000,Finished,6,2024,Qatar Grand Prix

In [6]:
year=2024

In [7]:
grouped = GP.groupby(['Year','Abbreviation','Position'])["Points"].agg('count').reset_index()
grouped.columns=['Year','Abbreviation','Position','Count']
grouped=grouped[grouped['Year']==year]
grouped=grouped.sort_values(by=['Position','Count'], ascending=[True,False])
grouped.head()

     Year Abbreviation  Position  Count
289  2024          VER         1      4
246  2024          NOR         1      1
259  2024          PIA         1      1
260  2024          PIA         2      2
227  2024          HAM         2      1

In [9]:
fig=px.bar(grouped, 
           x="Position", 
           y='Count', 
           color='Abbreviation',
        #    title="Sprint Race Position Counts By Driver for the {} F1 Season".format(year),
           height=800, 
           width=1200, 
           template="plotly_white",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "BEA": "#B6BABD",
                 "COL": "#37BEDD",
                 "DOO": "#0093cc",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LAW": "#6692FF",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            },
            )

fig.update_layout(
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=15),
    tickmode = 'linear',
    tick0 = 1,
    dtick = 1),
    xaxis = dict(tickfont = dict(size=15),
    tickmode = 'linear',
    tick0 = 1,
    dtick = 1),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5)
)
# fig.update_traces(marker={'size': 12})

In [10]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Count by Pos No./{}/Sprint Race Final Position Counts By Driver.html".format(year),full_html=False, include_plotlyjs='cdn')

In [11]:
#By Team

In [12]:
grouped_team = GP.groupby(['Year','TeamName','Position'])["Points"].agg('count').reset_index()
grouped_team.columns=['Year','Constructor','Position','Count']
grouped_team=grouped_team[grouped_team['Year']==year]
grouped_team=grouped_team.sort_values(by=['Position','Count'], ascending=[True,False])
grouped_team.head()

     Year      Constructor  Position  Count
238  2024  Red Bull Racing         1      4
213  2024          McLaren         1      2
214  2024          McLaren         2      3
191  2024          Ferrari         2      2
220  2024         Mercedes         2      1

In [13]:
fig_team=px.bar(grouped_team, 
           x="Position", 
           y='Count', 
           color='Constructor',
        #    title="Sprint Race Position Counts By Team for the {} F1 Season".format(year),
           height=800, 
           width=1200, 
           template="plotly_white",
           color_discrete_map={
                 "Alpine": "#0093cc",
                 "Aston Martin": "#229971",
                 "Ferrari": "#E80020",
                 "Haas F1 Team": "#B6BABD",
                 "Kick Sauber": "#52e252",
                 "McLaren": "#FF8000",
                 "Mercedes": "#27F4D2",
                 "RB": "#6692FF",
                 "Red Bull Racing": "#3671C6",
                 "Williams": "#64C4FF" ,
                 "Alfa Romeo":"#C92D4B",
                 "Alfa Romeo Racing":"#C92D4B",
                 "AlphaTauri":"#5E8FAA",
                 "Racing Point":"#F596C8",
                 "Renault":"#FFF500",
                 "Toro Rosso":"#469bff",
                 "Force India":"#F596C8",
                 "Sauber":"#9B0000"
            },
            )

fig_team.update_layout(
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15),
    tickmode = 'linear',
    tick0 = 1,
    dtick = 1),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

# fig.update_traces(marker={'size': 12})

In [14]:
fig_team.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Count by Pos No./{}/Sprint Race Final Position Counts By Team.html".format(year),full_html=False, include_plotlyjs='cdn')

In [15]:
#Sprint Qualy

In [16]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_sprint_qualifying`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_qualy = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [17]:
GP_qualy=df_bq2_qualy
GP_qualy=GP_qualy.fillna(0)
GP_qualy["Position"]=GP_qualy["Position"].astype(int)
GP_qualy["GridPosition"]=GP_qualy["GridPosition"].astype(int)
GP_qualy["Points"]=GP_qualy["Points"].astype(int)
GP_qualy=GP_qualy[GP_qualy["Position"]!=0]
GP_qualy.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
0,43,F COLAPINTO,COL,,Williams,64C4FF,,Franco,Colapinto,Franco Colapinto,None,ARG,10,,0,0 days 00:01:34.606000,0 days 00:01:33.952000,0 days 00:01:34.406000,NaT,,0,2024,United States Grand Prix
1,43,F COLAPINTO,COL,,Williams,64C4FF,,Franco,Colapinto,Franco Colapinto,None,ARG,14,,0,0 days 00:01:10.470000,0 days 00:01:10.275000,NaT,NaT,,0,2024,São Paulo Grand Prix
2,81,O PIASTRI,PIA,,McLaren,FF8000,,Oscar,Piastri,Oscar Piastri,https://media.formula1.com/d_driver_fallback_i...,AUS,6,,0,0 days 00:01:28.056000,0 days 00:01:28.163000,0 days 00:01:28.161000,NaT,,0,2024,Miami Grand Prix
3,81,O PIASTRI,PIA,,McLaren,FF8000,,Oscar,Piastri,Oscar Piastri,https://media.formula1.com/d_driver_fallback_i...,AUS,8,,0,0 days 00:01:36.542000,0 days 00:01:35.853000,0 days 00:02:00.990000,NaT,,0,2024,Chinese Grand Prix
4,81,O PIASTRI,PIA,,McLaren,F58020,,Oscar,Piastri,Oscar Piastri,https://www.formula1.com/content/dam/fom-websi...,AUS,11,,0,0 days 00:01:44.179000,0 days 00:01:43.427000,NaT,NaT,,0,2023,Azerbaijan Grand Prix

In [18]:
grouped_qualy = GP_qualy.groupby(['Year','Abbreviation','Position'])["Points"].agg('count').reset_index()
grouped_qualy.columns=['Year','Abbreviation','Position','Count']
grouped_qualy=grouped_qualy[grouped_qualy['Year']==year]
grouped_qualy=grouped_qualy.sort_values(by=['Position','Count'], ascending=[True,False])
grouped_qualy.head()

     Year Abbreviation  Position  Count
190  2024          VER         1      3
147  2024          NOR         1      2
161  2024          PIA         1      1
148  2024          NOR         2      2
169  2024          RUS         2      2

In [19]:
fig_qualy=px.bar(grouped_qualy, 
           x="Position", 
           y='Count', 
           color='Abbreviation',
        #    title="Race Position Counts By Driver for the {} F1 Season".format(year),
           height=800, 
           width=1200, 
           template="plotly_white",
           color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BEA": "#B6BABD", 
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LAW": "#6692FF",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            },
            )

fig_qualy.update_layout(
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15),
    tickmode = 'linear',
    tick0 = 1,
    dtick = 1),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5)
)
# fig.update_traces(marker={'size': 12})

In [20]:
fig_qualy.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Count by Pos No./{}/Sprint Qualifying Final Position Counts By Driver.html".format(year),full_html=False, include_plotlyjs='cdn')

In [21]:
#By Team

In [22]:
grouped_team_qualy = GP_qualy.groupby(['Year','TeamName','Position'])["Points"].agg('count').reset_index()
grouped_team_qualy.columns=['Year','Constructor','Position','Count']
grouped_team_qualy=grouped_team_qualy[grouped_team_qualy['Year']==year]
grouped_team_qualy=grouped_team_qualy.sort_values(by=['Position','Count'], ascending=[True,False])
grouped_team_qualy.head()

     Year      Constructor  Position  Count
125  2024          McLaren         1      3
149  2024  Red Bull Racing         1      3
133  2024         Mercedes         2      3
126  2024          McLaren         2      2
101  2024          Ferrari         2      1

In [23]:
fig_team_qualy=px.bar(grouped_team_qualy, 
           x="Position", 
           y='Count', 
           color='Constructor',
        #    title="Race Position Counts By Team for the {} F1 Season".format(year),
           height=800, 
           width=1200, 
           template="plotly_white",
           color_discrete_map={
                 "Alpine": "#0093cc",
                 "Aston Martin": "#229971",
                 "Ferrari": "#E80020",
                 "Haas F1 Team": "#B6BABD",
                 "Kick Sauber": "#52e252",
                 "McLaren": "#FF8000",
                 "Mercedes": "#27F4D2",
                 "RB": "#6692FF",
                 "Red Bull Racing": "#3671C6",
                 "Williams": "#64C4FF" ,
                 "Alfa Romeo":"#C92D4B",
                 "Alfa Romeo Racing":"#C92D4B",
                 "AlphaTauri":"#5E8FAA",
                 "Racing Point":"#F596C8",
                 "Renault":"#FFF500",
                 "Toro Rosso":"#469bff",
                 "Force India":"#F596C8",
                 "Sauber":"#9B0000"
            },
            )

fig_team_qualy.update_layout(
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15),
    tickmode = 'linear',
    tick0 = 1,
    dtick = 1),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

# fig.update_traces(marker={'size': 12})

In [24]:
fig_team_qualy.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Count by Pos No./{}/Sprint Qualifying Final Position Counts By Team.html".format(year),full_html=False, include_plotlyjs='cdn')