In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
import sys, requests
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
query2=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.race_lap_time`
# WHERE YEAR=2024
# AND GP='Saudi Arabian Grand Prix'
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

In [4]:
query_all_laps=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.race_lap_time`
UNION ALL
SELECT * FROM `perceptive-ivy-290216.f1_api.final_driver_positions_all`
"""
track_all_laps=pandas_gbq.read_gbq(query_all_laps,project_id,dialect='standard')

Downloading: 100%|██████████|

In [ ]:
race="Japanese Grand Prix"
years=2025

In [6]:
track2=track3[(track3["GP"]==race)&(track3["Year"]==years)]

In [7]:
#Get Final Pos to order the final plot
track_all_laps_2=track_all_laps[(track_all_laps["GP"]==race)&(track_all_laps["Year"]==years)]
final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]

In [8]:
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]
Drivers=(track2['Driver'].unique())

In [9]:
track_all_laps_2.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
28852,0 days 02:24:50.905000,LAW,30,0 days 00:01:36.437000,52.0,3.0,NaT,NaT,0 days 00:00:25.697000,0 days 00:00:29.139000,0 days 00:00:41.601000,0 days 02:23:40.205000,0 days 02:24:09.344000,0 days 02:24:50.945000,NaN,275.0,265.0,317.0,False,HARD,22.0,True,Red Bull Racing,0 days 02:23:14.468000,NaT,1,16.0,False,,False,True,2025,Chinese Grand Prix
28853,0 days 02:26:28.045000,LAW,30,0 days 00:01:37.140000,53.0,3.0,NaT,NaT,0 days 00:00:25.946000,0 days 00:00:29.248000,0 days 00:00:41.946000,0 days 02:25:16.891000,0 days 02:25:46.139000,0 days 02:26:28.085000,282.0,274.0,264.0,313.0,False,HARD,23.0,True,Red Bull Racing,0 days 02:24:50.905000,NaT,1,16.0,False,,False,True,2025,Chinese Grand Prix
28854,0 days 02:28:05.291000,LAW,30,0 days 00:01:37.246000,54.0,3.0,NaT,NaT,0 days 00:00:26.013000,0 days 00:00:29.280000,0 days 00:00:41.953000,0 days 02:26:54.098000,0 days 02:27:23.378000,0 days 02:28:05.331000,284.0,274.0,262.0,317.0,False,HARD,24.0,True,Red Bull Racing,0 days 02:26:28.045000,NaT,1,16.0,False,,False,True,2025,Chinese Grand Prix
28855,0 days 02:29:42.079000,LAW,30,0 days 00:01:36.788000,55.0,3.0,NaT,NaT,0 days 00:00:25.843000,0 days 00:00:29.112000,0 days 00:00:41.833000,0 days 02:28:31.174000,0 days 02:29:00.286000,0 days 02:29:42.119000,NaN,274.0,263.0,319.0,False,HARD,25.0,True,Red Bull Racing,0 days 02:28:05.291000,NaT,1,16.0,False,,False,True,2025,Chinese Grand Prix
28856,0 days 02:31:19.275000,LAW,30,0 days 00:01:37.196000,56.0,3.0,NaT,NaT,0 days 00:00:25.810000,0 days 00:00:29.354000,0 days 00:00:42.032000,0 days 02:30:07.929000,0 days 02:30:37.283000,0 days 02:31:19.315000,285.0,274.0,265.0,316.0,False,HARD,26.0,True,Red Bull Racing,0 days 02:29:42.079000,NaT,1,16.0,False,,False,True,2025,Chinese Grand Prix

In [10]:
stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
stints = stints.rename(columns={"LapNumber": "StintLength"})
stints.head()

  Driver  Stint Compound  StintLength
0    ALB    1.0   MEDIUM           20
1    ALB    2.0     HARD           36
2    ALO    1.0   MEDIUM            4
3    ANT    1.0   MEDIUM           12
4    ANT    2.0     HARD           44

In [28]:
#Use commented when the bars don't align with final race positions
# stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Stint','Position'])

# stint_with_pos["Total"]=stint_with_pos["Compound"].astype(str)+ " " +stint_with_pos["Stint"].astype(str)
stint_with_pos=stint_with_pos.reset_index(drop=True)
stint_with_pos.head()

  Driver  Stint Compound  StintLength  Position
0    PIA    1.0   MEDIUM           14       1.0
1    NOR    1.0   MEDIUM           15       2.0
2    RUS    1.0   MEDIUM           14       3.0
3    VER    1.0   MEDIUM           13       4.0
4    OCO    1.0   MEDIUM           11       5.0

In [29]:
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(int)
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(str)
stint_with_pos["LapNumber"]=stint_with_pos.groupby("Driver")["StintLength"].cumsum() #This will give lap number on stint final lap
stint_with_pos["LapNumber_Prior"]=stint_with_pos.groupby("Driver")["LapNumber"].shift(1) #Get prior lap
stint_with_pos=stint_with_pos.fillna(0)
stint_with_pos["Img_Loc"]=(stint_with_pos["LapNumber"]+stint_with_pos["LapNumber_Prior"])/2 #This will make the placement for the image around the center
stint_with_pos.head()

,Driver,Stint,Compound,StintLength,Position,LapNumber,LapNumber_Prior,Img_Loc
0,PIA,1,MEDIUM,14,1.0,14,0.0,7.0
1,NOR,1,MEDIUM,15,2.0,15,0.0,7.5
2,RUS,1,MEDIUM,14,3.0,14,0.0,7.0
3,VER,1,MEDIUM,13,4.0,13,0.0,6.5
4,OCO,1,MEDIUM,11,5.0,11,0.0,5.5

In [30]:
fig=px.bar(
    stint_with_pos,
    y="Driver",
    x='StintLength',
    text="StintLength",
    orientation='h',
    barmode='stack',
    # color='Compound',
    template="simple_white",
    title="<b>Tyre Strategies for the {} {}</b>".format(year,gp),
    height=800, width=1200,
    hover_data=["Position","Stint","Compound","LapNumber"],
    color_discrete_map={
                 "SOFT": "#F91536",
                 "MEDIUM": "#ffdf00 ",
                 "HARD":"#c8c8c8 ",
                 "INTERMEDIATE":"#009E60 ",
                 "WET":"#3671C6"
    }
)
fig.update_layout(
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    xaxis_title="<b>Lap Number</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)

for x,y,z in zip(stint_with_pos.Img_Loc, stint_with_pos.Compound, stint_with_pos.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==y:
      image=str(png)
      fig.add_layout_image(
          x=x,
          y=z,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=4,
          sizey=4,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
        yaxis={'categoryorder':'total descending'},  
        hoverlabel=dict(
        bgcolor="Black",
        font_size=20,
        font_family="PT Sans Narrow",

    ),
    margin=dict(l=5, r=5, t=35, b=5),
    )

fig['layout']['yaxis']['autorange'] = "reversed"

fig.update_traces(marker_line_width=3, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

fig.update_yaxes(ticksuffix = "  ")

fig.update_traces(marker_color='#a2a2a2')

fig.show()

In [31]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Tyre Strat/{}/{} {} Tyre Strategies.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi Tracks

In [14]:
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2020
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    track_all_laps_2=track_all_laps[(track_all_laps["GP"]==i)&(track_all_laps["Year"]==year_multi)]
    final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    Drivers=(track2['Driver'].unique())
    stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
    stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
    stints = stints.rename(columns={"LapNumber": "StintLength"})
    stints.head()
    stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
    stint_with_pos.head()
    fig=px.bar(
        stint_with_pos,
        y="Driver",
        x='StintLength',
        text="StintLength",
        orientation='h',
        barmode='stack',
        color='Compound',
        template="simple_white",
        title="<b>Tyre Strategies for the {} {}</b>".format(year_multi,i),
        height=800, width=1200,
        hover_data=["Position"],
        color_discrete_map={
                    "SOFT": "#F91536",
                    "MEDIUM": "#ffdf00 ",
                    "HARD":"#c8c8c8 ",
                    "INTERMEDIATE":"#009E60 ",
                    "WET":"#3671C6"
        }
    )
    fig.update_layout(
        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        xaxis_title="<b>Lap Number</b>",
        yaxis_title="<b>Driver</b>",
        title_x=0.5,
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )

    fig.update_layout(yaxis={'categoryorder':'total descending'},    
            hoverlabel=dict(
            bgcolor="Black",
            font_size=16,
            font_family="PT Sans Narrow"
        ),
        margin=dict(l=5, r=5, t=35, b=5),
        )

    fig['layout']['yaxis']['autorange'] = "reversed"

    fig.update_traces(marker_line_width=1, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

    fig.update_yaxes(ticksuffix = "  ")
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Tyre Strat/{}/{} {} Tyre Strategies.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')