In [313]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [314]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [315]:
query2=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.race_lap_time`
# WHERE YEAR=2024
# AND GP='Saudi Arabian Grand Prix'
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [316]:
query_all_laps=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.race_lap_time`
UNION ALL
SELECT * FROM `perceptive-ivy-290216.f1_api.final_driver_positions_all`
"""
track_all_laps=pandas_gbq.read_gbq(query_all_laps,project_id,dialect='standard')

Downloading: 100%|██████████|

In [317]:
race="Australian Grand Prix"
years=2025

In [318]:
track2=track3[(track3["GP"]==race)&(track3["Year"]==years)]

In [319]:
#Get Final Pos to order the final plot
track_all_laps_2=track_all_laps[(track_all_laps["GP"]==race)&(track_all_laps["Year"]==years)]
final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]

In [320]:
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]
Drivers=(track2['Driver'].unique())

In [321]:
track_all_laps_2.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
27767,0 days 02:47:44.697000,BEA,87,0 days 00:01:31.366000,53.0,7.0,NaT,NaT,0 days 00:00:31.993000,0 days 00:00:19.286000,0 days 00:00:40.087000,0 days 02:46:45.387000,0 days 02:47:04.673000,0 days 02:47:44.760000,269.0,292.0,283.0,287.0,False,INTERMEDIATE,9.0,True,Haas F1 Team,0 days 02:46:13.331000,NaT,1,14.0,False,,False,True,2025,Australian Grand Prix
27768,0 days 02:49:15.187000,BEA,87,0 days 00:01:30.490000,54.0,7.0,NaT,NaT,0 days 00:00:31.429000,0 days 00:00:19.147000,0 days 00:00:39.914000,0 days 02:48:16.189000,0 days 02:48:35.336000,0 days 02:49:15.250000,NaN,293.0,283.0,289.0,False,INTERMEDIATE,10.0,True,Haas F1 Team,0 days 02:47:44.697000,NaT,1,14.0,False,,False,True,2025,Australian Grand Prix
27769,0 days 02:50:46.471000,BEA,87,0 days 00:01:31.284000,55.0,7.0,NaT,NaT,0 days 00:00:31.538000,0 days 00:00:19.483000,0 days 00:00:40.263000,0 days 02:49:46.788000,0 days 02:50:06.271000,0 days 02:50:46.534000,267.0,292.0,282.0,287.0,False,INTERMEDIATE,11.0,True,Haas F1 Team,0 days 02:49:15.187000,NaT,1,14.0,False,,False,True,2025,Australian Grand Prix
27770,0 days 02:52:16.697000,BEA,87,0 days 00:01:30.226000,56.0,7.0,NaT,NaT,0 days 00:00:31.349000,0 days 00:00:19.207000,0 days 00:00:39.670000,0 days 02:51:17.883000,0 days 02:51:37.090000,0 days 02:52:16.760000,268.0,294.0,283.0,290.0,False,INTERMEDIATE,12.0,True,Haas F1 Team,0 days 02:50:46.471000,NaT,1,14.0,False,,False,True,2025,Australian Grand Prix
27771,0 days 02:53:47.250000,BEA,87,0 days 00:01:30.553000,57.0,7.0,NaT,NaT,0 days 00:00:31.384000,0 days 00:00:19.175000,0 days 00:00:39.994000,0 days 02:52:48.144000,0 days 02:53:07.319000,0 days 02:53:47.313000,265.0,288.0,286.0,282.0,False,INTERMEDIATE,13.0,True,Haas F1 Team,0 days 02:52:16.697000,NaT,1,14.0,False,,False,True,2025,Australian Grand Prix

In [322]:
stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
stints = stints.rename(columns={"LapNumber": "StintLength"})
stints.head()

  Driver  Stint      Compound  StintLength
0    ALB    1.0  INTERMEDIATE            2
1    ALB    2.0  INTERMEDIATE            1
2    ALB    3.0  INTERMEDIATE            1
3    ALB    4.0  INTERMEDIATE           29
4    ALB    5.0        MEDIUM           11

In [323]:
#Use commented when the bars don't align with final race positions
# stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Stint','Position'])

# stint_with_pos["Total"]=stint_with_pos["Compound"].astype(str)+ " " +stint_with_pos["Stint"].astype(str)
stint_with_pos=stint_with_pos.reset_index(drop=True)
stint_with_pos.head()

  Driver  Stint      Compound  StintLength  Position
0    NOR    1.0  INTERMEDIATE            2       1.0
1    VER    1.0  INTERMEDIATE            2       2.0
2    RUS    1.0  INTERMEDIATE            2       3.0
3    ALB    1.0  INTERMEDIATE            2       4.0
4    ANT    1.0  INTERMEDIATE            2       5.0

In [324]:
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(int)
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(str)
stint_with_pos.head()

  Driver Stint      Compound  StintLength  Position
0    NOR     1  INTERMEDIATE            2       1.0
1    VER     1  INTERMEDIATE            2       2.0
2    RUS     1  INTERMEDIATE            2       3.0
3    ALB     1  INTERMEDIATE            2       4.0
4    ANT     1  INTERMEDIATE            2       5.0

In [325]:
fig=px.bar(
    stint_with_pos,
    y="Driver",
    x='StintLength',
    text="StintLength",
    orientation='h',
    barmode='stack',
    color='Compound',
    template="simple_white",
    title="<b>Tyre Strategies for the {} {}</b>".format(year,gp),
    height=800, width=1200,
    hover_data=["Position","Stint","Compound"],
    category_orders={'Stint': ['1','2','3','4','5','6','7']},
    color_discrete_map={
                 "SOFT": "#F91536",
                 "MEDIUM": "#ffdf00 ",
                 "HARD":"#c8c8c8 ",
                 "INTERMEDIATE":"#009E60 ",
                 "WET":"#3671C6"
    }
)
fig.update_layout(
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    xaxis_title="<b>Lap Number</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)

fig.update_layout(
        yaxis={'categoryorder':'total descending'},  
        hoverlabel=dict(
        bgcolor="Black",
        font_size=20,
        font_family="PT Sans Narrow",

    ),
    margin=dict(l=5, r=5, t=35, b=5),
    )

fig['layout']['yaxis']['autorange'] = "reversed"

fig.update_traces(marker_line_width=1, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

fig.update_yaxes(ticksuffix = "  ")


fig.show()

In [ ]:
fig, ax = plt.subplots(figsize=(5, 10))

for driver in drivers:
    driver_stints = stints.loc[stints["Driver"] == driver]

    previous_stint_end = 0
    for idx, row in driver_stints.iterrows():
        # each row contains the compound name and stint length
        # we can use these information to draw horizontal bars
        compound_color = fastf1.plotting.get_compound_color(row["Compound"],
                                                            session=session)
        plt.barh(
            y=driver,
            width=row["StintLength"],
            left=previous_stint_end,
            color=compound_color,
            edgecolor="black",
            fill=True
        )

        previous_stint_end += row["StintLength"]

In [326]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Tyre Strat/{}/{} {} Tyre Strategies.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi Tracks

In [14]:
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2020
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    track_all_laps_2=track_all_laps[(track_all_laps["GP"]==i)&(track_all_laps["Year"]==year_multi)]
    final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    Drivers=(track2['Driver'].unique())
    stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
    stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
    stints = stints.rename(columns={"LapNumber": "StintLength"})
    stints.head()
    stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
    stint_with_pos.head()
    fig=px.bar(
        stint_with_pos,
        y="Driver",
        x='StintLength',
        text="StintLength",
        orientation='h',
        barmode='stack',
        color='Compound',
        template="simple_white",
        title="<b>Tyre Strategies for the {} {}</b>".format(year_multi,i),
        height=800, width=1200,
        hover_data=["Position"],
        color_discrete_map={
                    "SOFT": "#F91536",
                    "MEDIUM": "#ffdf00 ",
                    "HARD":"#c8c8c8 ",
                    "INTERMEDIATE":"#009E60 ",
                    "WET":"#3671C6"
        }
    )
    fig.update_layout(
        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        xaxis_title="<b>Lap Number</b>",
        yaxis_title="<b>Driver</b>",
        title_x=0.5,
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )

    fig.update_layout(yaxis={'categoryorder':'total descending'},    
            hoverlabel=dict(
            bgcolor="Black",
            font_size=16,
            font_family="PT Sans Narrow"
        ),
        margin=dict(l=5, r=5, t=35, b=5),
        )

    fig['layout']['yaxis']['autorange'] = "reversed"

    fig.update_traces(marker_line_width=1, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

    fig.update_yaxes(ticksuffix = "  ")
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Tyre Strat/{}/{} {} Tyre Strategies.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')