In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
import sys, requests
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.race_lap_time`
# WHERE YEAR=2024
# AND GP='Saudi Arabian Grand Prix'
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
query_all_laps=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.race_lap_time`
UNION ALL
SELECT * FROM `perceptive-ivy-290216.f1_api.final_driver_positions_all`
"""
track_all_laps=pandas_gbq.read_gbq(query_all_laps,project_id,dialect='standard')

Downloading: 100%|██████████|

In [16]:
race="Qatar Grand Prix"
years=2025

In [17]:
track2=track3[(track3["GP"]==race)&(track3["Year"]==years)]

In [18]:
#Get Final Pos to order the final plot
track_all_laps_2=track_all_laps[(track_all_laps["GP"]==race)&(track_all_laps["Year"]==years)]
final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]

In [19]:
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]
Drivers=(track2['Driver'].unique())

In [20]:
track_all_laps_2.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
95049,0 days 01:56:13.468000,BEA,87,0 days 00:01:25.451000,37.0,3.0,NaT,NaT,0 days 00:00:31.672000,0 days 00:00:29.092000,0 days 00:00:24.687000,0 days 01:55:19.725000,0 days 01:55:48.817000,0 days 01:56:13.504000,240.0,285.0,280.0,305.0,False,HARD,5.0,True,Haas F1 Team,0 days 01:54:48.017000,NaT,1,18.0,False,,False,True,2025,Qatar Grand Prix
95050,0 days 01:57:39.045000,BEA,87,0 days 00:01:25.577000,38.0,3.0,NaT,NaT,0 days 00:00:31.643000,0 days 00:00:29.248000,0 days 00:00:24.686000,0 days 01:56:45.147000,0 days 01:57:14.395000,0 days 01:57:39.081000,241.0,286.0,280.0,309.0,False,HARD,6.0,True,Haas F1 Team,0 days 01:56:13.468000,NaT,1,18.0,False,,False,True,2025,Qatar Grand Prix
95051,0 days 01:59:04.382000,BEA,87,0 days 00:01:25.337000,39.0,3.0,NaT,NaT,0 days 00:00:31.577000,0 days 00:00:29.115000,0 days 00:00:24.645000,0 days 01:58:10.658000,0 days 01:58:39.773000,0 days 01:59:04.418000,242.0,287.0,281.0,308.0,False,HARD,7.0,True,Haas F1 Team,0 days 01:57:39.045000,NaT,1,18.0,False,,False,True,2025,Qatar Grand Prix
95052,0 days 02:00:34.535000,BEA,87,0 days 00:01:30.153000,40.0,3.0,NaT,0 days 02:00:30.569000,0 days 00:00:31.397000,0 days 00:00:29.350000,0 days 00:00:29.406000,0 days 01:59:35.815000,0 days 02:00:05.165000,0 days 02:00:34.571000,240.0,288.0,NaN,323.0,False,HARD,8.0,True,Haas F1 Team,0 days 01:59:04.382000,NaT,1,19.0,False,,False,False,2025,Qatar Grand Prix
95053,0 days 02:02:35.669000,BEA,87,0 days 00:02:01.134000,41.0,4.0,0 days 02:01:07.908000,0 days 02:02:31.106000,0 days 00:01:02.329000,0 days 00:00:28.786000,0 days 00:00:30.019000,0 days 02:01:36.900000,0 days 02:02:05.686000,0 days 02:02:35.705000,244.0,285.0,NaN,182.0,False,HARD,9.0,False,Haas F1 Team,0 days 02:00:34.535000,NaT,1,19.0,False,,False,False,2025,Qatar Grand Prix

In [21]:
stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
stints = stints.rename(columns={"LapNumber": "StintLength"})
stints.head()

  Driver  Stint Compound  StintLength
0    ALB    1.0     HARD            7
1    ALB    2.0   MEDIUM           25
2    ALB    3.0   MEDIUM           25
3    ALO    1.0   MEDIUM            7
4    ALO    2.0   MEDIUM           25

In [22]:
#Use commented when the bars don't align with final race positions
# stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Stint','Position'])

# stint_with_pos["Total"]=stint_with_pos["Compound"].astype(str)+ " " +stint_with_pos["Stint"].astype(str)
stint_with_pos=stint_with_pos.reset_index(drop=True)
stint_with_pos.head()

  Driver  Stint Compound  StintLength  Position
0    VER    1.0   MEDIUM            7       1.0
1    PIA    1.0   MEDIUM           24       2.0
2    SAI    1.0   MEDIUM            7       3.0
3    NOR    1.0   MEDIUM           25       4.0
4    ANT    1.0   MEDIUM            7       5.0

In [23]:
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(int)
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(str)
stint_with_pos["LapNumber"]=stint_with_pos.groupby("Driver")["StintLength"].cumsum() #This will give lap number on stint final lap
stint_with_pos["LapNumber_Prior"]=stint_with_pos.groupby("Driver")["LapNumber"].shift(1) #Get prior lap
stint_with_pos=stint_with_pos.fillna(0)
stint_with_pos["Img_Loc"]=(stint_with_pos["LapNumber"]+stint_with_pos["LapNumber_Prior"])/2 #This will make the placement for the image around the center
stint_with_pos.head()

,Driver,Stint,Compound,StintLength,Position,LapNumber,LapNumber_Prior,Img_Loc
0,VER,1,MEDIUM,7,1.0,7,0.0,3.5
1,PIA,1,MEDIUM,24,2.0,24,0.0,12.0
2,SAI,1,MEDIUM,7,3.0,7,0.0,3.5
3,NOR,1,MEDIUM,25,4.0,25,0.0,12.5
4,ANT,1,MEDIUM,7,5.0,7,0.0,3.5

In [24]:
fig=px.bar(
    stint_with_pos,
    y="Driver",
    x='StintLength',
    text="StintLength",
    orientation='h',
    barmode='stack',
    # color='Compound',
    template="simple_white",
    title="<b>Tyre Strategies for the {} {}</b>".format(year,gp),
    height=800, width=1200,
    hover_data=["Position","Stint","Compound","LapNumber"],
    color_discrete_map={
                 "SOFT": "#F91536",
                 "MEDIUM": "#ffdf00 ",
                 "HARD":"#c8c8c8 ",
                 "INTERMEDIATE":"#009E60 ",
                 "WET":"#3671C6"
    }
)
fig.update_layout(
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    xaxis_title="<b>Lap Number</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)

for x,y,z in zip(stint_with_pos.Img_Loc, stint_with_pos.Compound, stint_with_pos.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==y:
      image=str(png)
      fig.add_layout_image(
          x=x,
          y=z,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=4,
          sizey=4,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
        yaxis={'categoryorder':'total descending'},  
        hoverlabel=dict(
        bgcolor="Black",
        font_size=20,
        font_family="PT Sans Narrow",

    ),
    margin=dict(l=5, r=5, t=35, b=5),
    )

fig['layout']['yaxis']['autorange'] = "reversed"

fig.update_traces(marker_line_width=3, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

fig.update_yaxes(ticksuffix = "  ")

fig.update_traces(marker_color='#a2a2a2')

fig.show()

In [25]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Tyre Strat/{}/{} {} Tyre Strategies.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi Tracks

In [17]:
#2025
race_multi=["Japanese Grand Prix","Bahrain Grand Prix","Saudi Arabian Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Spanish Grand Prix","Canadian Grand Prix","Austrian Grand Prix","British Grand Prix","Belgian Grand Prix","Hungarian Grand Prix","Dutch Grand Prix","Italian Grand Prix","Azerbaijan Grand Prix","Singapore Grand Prix","United States Grand Prix","Mexico City Grand Prix","São Paulo Grand Prix"]
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2025
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    track_all_laps_2=track_all_laps[(track_all_laps["GP"]==i)&(track_all_laps["Year"]==year_multi)]
    final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    Drivers=(track2['Driver'].unique())
    stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
    stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
    stints = stints.rename(columns={"LapNumber": "StintLength"})
    stints.head()
    stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
    stint_with_pos.head()
    fig=px.bar(
        stint_with_pos,
        y="Driver",
        x='StintLength',
        text="StintLength",
        orientation='h',
        barmode='stack',
        color='Compound',
        template="simple_white",
        title="<b>Tyre Strategies for the {} {}</b>".format(year_multi,i),
        height=800, width=1200,
        hover_data=["Position"],
        color_discrete_map={
                    "SOFT": "#F91536",
                    "MEDIUM": "#ffdf00 ",
                    "HARD":"#c8c8c8 ",
                    "INTERMEDIATE":"#009E60 ",
                    "WET":"#3671C6"
        }
    )
    fig.update_layout(
        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        xaxis_title="<b>Lap Number</b>",
        yaxis_title="<b>Driver</b>",
        title_x=0.5,
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )

    fig.update_layout(yaxis={'categoryorder':'total descending'},    
            hoverlabel=dict(
            bgcolor="Black",
            font_size=16,
            font_family="PT Sans Narrow"
        ),
        margin=dict(l=5, r=5, t=35, b=5),
        )

    fig['layout']['yaxis']['autorange'] = "reversed"

    fig.update_traces(marker_line_width=1, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

    fig.update_yaxes(ticksuffix = "  ")
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Tyre Strat/{}/{} {} Tyre Strategies.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')